#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("mhartl-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
let data = [];
text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if(phrase.palindrome()){
        console.log("検出されたパリンドローム:",line);
        data.push(line);
    }
});
fs.writeFile("file1.txt", data.join("\n"),(err) => {
    if(err) throw err;
    console.log("正常に書き込みしました");
});
